### PR TITLE
Feature/notify project managers

### PR DESCRIPTION
**Pull request by prasannamahajan**
- Sending notification to project manager when easycla won't be able to do cla checks
 he/she update/delete easycla github app.

### CODE REVIEW

**Comment by prasannamahajan** [comment]
Added unit test case

**Comment by wanyaland** [comment]
> Added unit test case

Could you shift the test file to cla/tests folder as thats the proposed structure

**Comment by dealako** [comment]
Yes, sorry @prasannamahajan - can you move the tests to the test folder - @wanyaland has restructured where our tests go (recently).  You will need to rebase/merge.

**Comment by prasannamahajan** [comment]
@dealako , @wanyaland  Re-based branch with master

**Pull request merged**
