### PR TITLE
Explain missing email issue in error message

### PR DESCRIPTION
**Pull request by kit1980**
The current error message is not very clear and we've had multiple users in the PyTorch repo having problems with resolving this.

### CODE REVIEW

**Review by WillsonHG — CHANGES_REQUESTED** [review]
Thank you for your PR. We settled on the message specified in the last comment on this issue. https://github.com/communitybridge/easycla/issues/3847 to specify the missing GitHub ID. We also thought it best not to add a solution into the message text, since many times the reverse is true (needing to update the git config file to the correct email.) WDYT about changing your commit to the message in that comment?

**Comment by kit1980** [comment]
> Thank you for your PR. We settled on the message specified in the last comment on this issue. #3847 to specify the missing GitHub ID. We also thought it best not to add a solution into the message text, since many times the reverse is true (needing to update the git config file to the correct email.) WDYT about changing your commit to the message in that comment?

The message from #3847 is definitely better then the current one in main.

My concern is that people will not realize that they used a different email and still will not be able to resolve the issue themselves.
Maybe still mention the .patch page so they quickly see the exact email address used?

And I understand the hesitation to add a solution into the message text, although in my experience helping multiple people with this issue in the PyTorch repo, in all but one case the desired solution was to add the email to the GitHub profile.

**Comment by WillsonHG** [comment]
The email address for the commit (xxxxxx) is not linked to the GitHub account, preventing the EasyCLA check. Consult [Article Help](https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=86641302) and [GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve. (To view the commit email address, add `.patch` at the end of this PR page's URL.) For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

**Comment by WillsonHG** [comment]
Hi @kit1980  would you like to amend your commit to the above and resubmit?

**Comment by kit1980** [comment]
> Hi @kit1980 would you like to amend your commit to the above and resubmit?

@WillsonHG updated, please take a look.

**Comment by kit1980** [comment]
I'll rebase and sign the DCO if the change looks good.

**Comment by kit1980** [comment]
Rebased and force-pushed to fix DCO.

**Review by mlehotskylf — APPROVED** [review]

**Review by thakurveerendras — APPROVED** [review]

**Comment by thakurveerendras** [comment]
Thanks @kit1980 for your contribution,
Verified issue on Dev environment & found that above changes are proper & accepted by @mlehotskylf , @jarias-lfx , @WillsonHG 

Refer testing details 
1. Link added on commit are proper & redirecting user to correct page

- **this Help Article** : https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=86641302
- **GitHub Help** : https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user
- **please submit a support request ticket**. : https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4
2.  MISSING ID ON COMMIT & NOT COVERED  cla boat appears on same commit .
3. Refer PR : https://github.com/sun-test-org/repo1/pull/69


Refer missing email error message : 

> ❌ The email address for the commit (https://github.com/sun-test-org/repo1/commit/2d6eeec7147eb74450832f027c10c559fae783e7) is not linked to the GitHub account, preventing the EasyCLA check. Consult [this Help Article](https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=86641302) and [GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve. (To view the commit's email address, add .patch at the end of this PR page's URL.) For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

image

**Comment by thakurveerendras** [comment]
Fixes are properly deployed on production , Refer PR https://github.com/CLATestOrg/VulDetect1/pull/33
image

**Pull request merged**
