### PR TITLE
Add support for embargo acknowledgement in python and golang backends

### PR DESCRIPTION
**Pull request by lukaszgryglicki**
Adding boolean property `signature_embargo_acked` to `cla-[env]-signatures` DynamoDB table and support in python backend.

This property is set to true on all new signatures created, and is not changed for existing signatures. So when a signature is updated - this field is either not changed or set to false (default values), while new signatures have this property set to `true`.

This is for the ticket: https://github.com/communitybridge/easycla/issues/4482.

This can only be merged when:
- UI is updated with new embargo checkbox that only allows proceeding when checked.

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
@mlehotskylf CI failures are not related to this PR and `lint-test-build` seems to be stalled.

**Comment by lukaszgryglicki** [comment]
`lint-test-build` still blocks this @mlehotskylf and other two CI failures aren't related to this PR as they happen for all PRs.

**Review by nickmango — DISMISSED** [review]
lgtm

**Review by nickmango — APPROVED** [review]
lgtm

**Pull request merged**
